### ISSUE TITLE
thread 'main' panicked at 'Can't read in game folder: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4

### ISSUE THREAD

**Issue by ibrokemypie** [nicohman/eidolon#4]
$ RUST_BACKTRACE=1 eidolon imports ~/.steam/steam/steamapps/common/
Reading in directory: /home/conor/.steam/steam/steamapps/common/
Attempting import on Stardew Valley
Creating game registry named stardew_valley.
thread 'main' panicked at 'Can't read in game folder: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_main
  16: <unknown>

**Comment by nicohman** [comment]
Okay, this isn't an error, just an example of incorrect usage/ unclear documentation. If you want to add steam games, you should be running `eidolonn update` after editing ~/.config/eidolon/config for yoour steam directories. The imports command is intended for drm-free games. If you were confused about update possibly not working, that's due to a bug in the default config, which is now fixed. So, in conclusion: Update eidolon, and use the update command instead of imports for steam games. My apologies for the documentation possibly being unclear.
