### ISSUE TITLE
Running wine games from .lnk files

### ISSUE THREAD

**Issue by lukeoftheaura** [nicohman/eidolon#7]
I have some games (touhou project games mainly) that have to be run though .lnk files rather than the exe directly (due to the way the patcher works and the fact it requires certain arguments to be passed). Is it possible to add these as wine games in eidolon?

**Comment by nicohman** [comment]
Not right this instant(well, I suppose that you could make a script that runs the .ink file, but that's just silly), but I'll see about adding that tonight. It shouldn't be difficult to fix--just a change in how it generates the launch scripts, to auto detect .inks and run them with `wine start` instead of `wine`. Sorry for the oversight and it'll be added soon!

**Comment by nicohman** [comment]
Actually, never mind this. .lnk files should actually work fine in eidolon--the `wine start` command no longer exists, and .lnk files can be run directly. Just add the .lnk file through wine_add, and you'll be fine. Let me know if there's an issue, though.
